### ISSUE TITLE
关于允许安装未知来源的权限请求

### ISSUE THREAD

**Issue by FangPro** [amorenew/Flutter-Root-installer#1]
大佬，想请教一下。在app内部更新下载完apk后如何调用申请允许安装未知来源的弹窗，而不是直接跳转到系统设置允许安装未知来源的界面。我用了很多安装app的插件，例如install_plugin,但都是在下载完资源后直接跳转到系统设置是否允许安装未知来源的界面，请问该如何调用允许安装未知来源的弹窗呢？谢谢。

**Comment by amreniouinnovent** [comment]
@404King 
There is a way for showing that popup
https://stackoverflow.com/questions/49828745/how-to-manage-installation-from-unknown-sources-in-android-oreo

I actually using this plugin on a rooted device so it will work on a rooted device only

**Comment by FangPro** [comment]
Thank you very much for your suggestion.
